### ISSUE TITLE
GCP-Bucket Plugin not found

### ISSUE THREAD

**Issue by carlonoelle** [verdaccio/monorepo#75]
**Describe the bug**

**To Reproduce**
- npm install -g verdaccio verdaccio-google-cloud

**Expected behavior**
GCP Storage Bucket as Storage

**Configuration File ** 
```
storage: ./storage
plugins: ~/.npm-global/lib
web:
  title: NPM Registry
  gravatar: false
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
logs:
  - { type: stdout, format: pretty, level: http }
listen: 'https://localhost:4430'
https:
  key: /home/cno/.config/verdaccio/verdaccio-key.pem
  cert: /home/cno/.config/verdaccio/verdaccio-cert.pem
  ca: /home/cno/.config/verdaccio/verdaccio-csr.pem
store:
  google-cloud:
   projectId: project-01 || env (GOOGLE_CLOUD_VERDACCIO_PROJECT_ID)
   kind: someRandonMetadataDatabaseKey
   bucket: my-bucket-name
   keyFilename: /path/project-01.json || env (GOOGLE_CLOUD_VERDACCIO_KEY)
   resumable: true
```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
```
warn --- config file  - /home/cno/testing.yaml
 error--- plugin not found. try npm install verdaccio-google-cloud
(node:12738) UnhandledPromiseRejectionWarning: Error:
        verdaccio-google-cloud plugin not found. try "npm install verdaccio-google-cloud"
    at /home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/plugin-loader.js:110:13
    at Array.map (<anonymous>)
    at loadPlugin (/home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/plugin-loader.js:62:37)
    at LocalStorage._loadStorePlugin (/home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/local-storage.js:853:47)
    at LocalStorage._loadStorage (/home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/local-storage.js:838:26)
    at new LocalStorage (/home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/local-storage.js:47:27)
    at Storage.init (/home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/storage.js:64:25)
    at _default (/home/cno/.npm-global/lib/node_modules/verdaccio/build/api/index.js:126:17)
    at startVerdaccio (/home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/bootstrap.js:48:22)
    at init (/home/cno/.npm-global/lib/node_modules/verdaccio/build/lib/cli.js:76:35)
(node:12738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', '-ddd' ]
npm info using npm@6.10.2
npm info using node@v12.8.1
npm verb config Skipping project config: /home/cno/.npmrc. (matches userconfig)
```

**Additional context**
Plugin is installed globally, but never found by verdaccio
